# Generated by Django 5.1.6 on 2025-04-19 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_courses_category_id_alter_courses_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.courses'),
        ),
    ]
